//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm16.Services
{
    using System;
    using System.Collections.Generic;

    using itcast.crm16.IServices;
    using itcast.crm16.model;
    using itcast.crm16.IRepository;
    using System.Linq.Expressions;

    public partial class NewServices : BaseBLL<New>, INewServices
    {
        INewRepository dal;
        public NewServices(INewRepository dal)
        {
            this.dal = dal;
            base.basedal = dal;
        }



        public List<New> NewPageList(int index, int typeId,string Name, out int count)
        {
            Expression<Func<New, bool>> where = (c => c.IsDelete == 0);
            if (typeId > 0)
            {
                if (string.IsNullOrWhiteSpace(Name))
                {
                    where = (c => c.IsDelete == 0 && c.TypeId == typeId);
                }
                else
                { where = (c => c.IsDelete == 0 && c.TypeId == typeId && c.Name.Contains(Name)); }
            }
            if (!string.IsNullOrWhiteSpace(Name))
            {
                where = (c => c.IsDelete == 0 && c.Name.Contains(Name));
            }
            return dal.QueryByPage(index, 10, out count, where,c => c.id);
        }
    }
}
