//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm16.model.ModelViews
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class wfWorkView
    {


        public int wfID { get; set; }
        [DisplayName("标题"), Required(ErrorMessage = "标题非空"), StringLength(50, ErrorMessage = "标题不能超过50个长度")]
        public string wfTitle { get; set; }
        public int wfStatus { get; set; }
        [DisplayName("备注"), StringLength(200, MinimumLength = 0, ErrorMessage = "标题不能超过200个长度")]
        public string wfRemark { get; set; }
        public int fCreatorID { get; set; }
        public System.DateTime fCreateTime { get; set; }
        public Nullable<int> fUpdateID { get; set; }
        public System.DateTime fUpdateTime { get; set; }

        public virtual ICollection<wfRequestFormView> wfRequestForm { get; set; }
        public virtual ICollection<wfWorkNodesView> wfWorkNodes { get; set; }
    }
}
