//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm16.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FS_SiteEntities : DbContext
    {
        public FS_SiteEntities()
            : base("name=FS_SiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Manage> Manage { get; set; }
        public DbSet<New> New { get; set; }
        public DbSet<NewType> NewType { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<VipUser> VipUser { get; set; }
        public DbSet<sysMenus> sysMenus { get; set; }
        public DbSet<sysUserInfo> sysUserInfo { get; set; }
    }
}
