//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm16.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class New
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Conent { get; set; }
        public bool IsComment { get; set; }
        public int IsDelete { get; set; }
        public string Author { get; set; }
        public Nullable<int> TypeId { get; set; }
        public System.DateTime CreatTime { get; set; }
        public string Creator { get; set; }
        public int Praise { get; set; }
        public int Look { get; set; }
    }
}
