//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm16.Site.WcfChatServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMsg", Namespace="http://schemas.datacontract.org/2004/07/itcast.crm16.ChatModel")]
    [System.SerializableAttribute()]
    public partial class ChatMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromRealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FromUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SendTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToRealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromRealName {
            get {
                return this.FromRealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FromRealNameField, value) != true)) {
                    this.FromRealNameField = value;
                    this.RaisePropertyChanged("FromRealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FromUserId {
            get {
                return this.FromUserIdField;
            }
            set {
                if ((this.FromUserIdField.Equals(value) != true)) {
                    this.FromUserIdField = value;
                    this.RaisePropertyChanged("FromUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageBody {
            get {
                return this.MessageBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageBodyField, value) != true)) {
                    this.MessageBodyField = value;
                    this.RaisePropertyChanged("MessageBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendTime {
            get {
                return this.SendTimeField;
            }
            set {
                if ((this.SendTimeField.Equals(value) != true)) {
                    this.SendTimeField = value;
                    this.RaisePropertyChanged("SendTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToRealName {
            get {
                return this.ToRealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToRealNameField, value) != true)) {
                    this.ToRealNameField = value;
                    this.RaisePropertyChanged("ToRealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToUserId {
            get {
                return this.ToUserIdField;
            }
            set {
                if ((this.ToUserIdField.Equals(value) != true)) {
                    this.ToUserIdField = value;
                    this.RaisePropertyChanged("ToUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cid {
            get {
                return this.cidField;
            }
            set {
                if ((this.cidField.Equals(value) != true)) {
                    this.cidField = value;
                    this.RaisePropertyChanged("cid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usp_GetHistoryMsg16_Result", Namespace="http://schemas.datacontract.org/2004/07/itcast.crm16.ChatModel")]
    [System.SerializableAttribute()]
    public partial class Usp_GetHistoryMsg16_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromRealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FromUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SendTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToRealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromRealName {
            get {
                return this.FromRealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FromRealNameField, value) != true)) {
                    this.FromRealNameField = value;
                    this.RaisePropertyChanged("FromRealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FromUserId {
            get {
                return this.FromUserIdField;
            }
            set {
                if ((this.FromUserIdField.Equals(value) != true)) {
                    this.FromUserIdField = value;
                    this.RaisePropertyChanged("FromUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageBody {
            get {
                return this.MessageBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageBodyField, value) != true)) {
                    this.MessageBodyField = value;
                    this.RaisePropertyChanged("MessageBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendTime {
            get {
                return this.SendTimeField;
            }
            set {
                if ((this.SendTimeField.Equals(value) != true)) {
                    this.SendTimeField = value;
                    this.RaisePropertyChanged("SendTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToRealName {
            get {
                return this.ToRealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToRealNameField, value) != true)) {
                    this.ToRealNameField = value;
                    this.RaisePropertyChanged("ToRealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToUserId {
            get {
                return this.ToUserIdField;
            }
            set {
                if ((this.ToUserIdField.Equals(value) != true)) {
                    this.ToUserIdField = value;
                    this.RaisePropertyChanged("ToUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cid {
            get {
                return this.cidField;
            }
            set {
                if ((this.cidField.Equals(value) != true)) {
                    this.cidField = value;
                    this.RaisePropertyChanged("cid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfChatServer.IChatManager")]
    public interface IChatManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/SetMessage")]
        void SetMessage(itcast.crm16.Site.WcfChatServer.ChatMsg model);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/SetMessage")]
        System.Threading.Tasks.Task SetMessageAsync(itcast.crm16.Site.WcfChatServer.ChatMsg model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManager/GetMessage", ReplyAction="http://tempuri.org/IChatManager/GetMessageResponse")]
        itcast.crm16.Site.WcfChatServer.ChatMsg[] GetMessage(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManager/GetMessage", ReplyAction="http://tempuri.org/IChatManager/GetMessageResponse")]
        System.Threading.Tasks.Task<itcast.crm16.Site.WcfChatServer.ChatMsg[]> GetMessageAsync(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManager/GetHistoryMsg", ReplyAction="http://tempuri.org/IChatManager/GetHistoryMsgResponse")]
        itcast.crm16.Site.WcfChatServer.Usp_GetHistoryMsg16_Result[] GetHistoryMsg(int userid, System.DateTime begintime, System.DateTime endtime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManager/GetHistoryMsg", ReplyAction="http://tempuri.org/IChatManager/GetHistoryMsgResponse")]
        System.Threading.Tasks.Task<itcast.crm16.Site.WcfChatServer.Usp_GetHistoryMsg16_Result[]> GetHistoryMsgAsync(int userid, System.DateTime begintime, System.DateTime endtime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatManagerChannel : itcast.crm16.Site.WcfChatServer.IChatManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatManagerClient : System.ServiceModel.ClientBase<itcast.crm16.Site.WcfChatServer.IChatManager>, itcast.crm16.Site.WcfChatServer.IChatManager {
        
        public ChatManagerClient() {
        }
        
        public ChatManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetMessage(itcast.crm16.Site.WcfChatServer.ChatMsg model) {
            base.Channel.SetMessage(model);
        }
        
        public System.Threading.Tasks.Task SetMessageAsync(itcast.crm16.Site.WcfChatServer.ChatMsg model) {
            return base.Channel.SetMessageAsync(model);
        }
        
        public itcast.crm16.Site.WcfChatServer.ChatMsg[] GetMessage(int userid) {
            return base.Channel.GetMessage(userid);
        }
        
        public System.Threading.Tasks.Task<itcast.crm16.Site.WcfChatServer.ChatMsg[]> GetMessageAsync(int userid) {
            return base.Channel.GetMessageAsync(userid);
        }
        
        public itcast.crm16.Site.WcfChatServer.Usp_GetHistoryMsg16_Result[] GetHistoryMsg(int userid, System.DateTime begintime, System.DateTime endtime) {
            return base.Channel.GetHistoryMsg(userid, begintime, endtime);
        }
        
        public System.Threading.Tasks.Task<itcast.crm16.Site.WcfChatServer.Usp_GetHistoryMsg16_Result[]> GetHistoryMsgAsync(int userid, System.DateTime begintime, System.DateTime endtime) {
            return base.Channel.GetHistoryMsgAsync(userid, begintime, endtime);
        }
    }
}
